[----------]
[ RUN      ] ExceptionTest.ReferenceError
exception_test.js:23
ReferenceError: fooBar is not defined

[  FAILED  ] ExceptionTest.ReferenceError (1 ms)
[ RUN      ] ExceptionTest.NotAFunctionError
exception_test.js:28
TypeError: object is not a function

[  FAILED  ] ExceptionTest.NotAFunctionError (1 ms)
[ RUN      ] ExceptionTest.ErrorInMatcherFactory
exception_test.js:32
TypeError: isNearNumber requires two number arguments

[  FAILED  ] ExceptionTest.ErrorInMatcherFactory (1 ms)
[ RUN      ] ExceptionTest.StackOverflow
RangeError: Maximum call stack size exceeded

[  FAILED  ] ExceptionTest.StackOverflow (1 ms)
[ RUN      ] ExceptionTest.UnknownPropertyOnLongFunction
exception_test.js:45
TypeError: Object function foo() {
    return 'asd';
  } has no method 'bar'

[  FAILED  ] ExceptionTest.UnknownPropertyOnLongFunction (1 ms)
[ RUN      ] ExceptionTest.ObjectLiteralException
{ name: 'SomeException' }

[  FAILED  ] ExceptionTest.ObjectLiteralException (1 ms)
[ RUN      ] ExceptionTest.CustomExceptionClassWithoutStack
{}

[  FAILED  ] ExceptionTest.CustomExceptionClassWithoutStack (1 ms)
[ RUN      ] ExceptionTest.CustomExceptionClassWithStack
exception_test.js:63
{}

[  FAILED  ] ExceptionTest.CustomExceptionClassWithStack (1 ms)
[ RUN      ] ExceptionTest.CustomExceptionClassWithToString
SomeException

[  FAILED  ] ExceptionTest.CustomExceptionClassWithToString (1 ms)
[ RUN      ] ExceptionTest.PassingTest
[       OK ] ExceptionTest.PassingTest (1 ms)
[----------]

[----------]
[ RUN      ] ThrowingConstructorTest.SomeTest
exception_test.js:77
Error: taco

[  FAILED  ] ThrowingConstructorTest.SomeTest (1 ms)
[----------]

[  FAILED  ]
